---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kubeflow-instance
  namespace: ${releaseNamespace}
spec:
  interval: 1m0s
  ref:
    tag: v1.8.1
  timeout: 15m0s
  url: https://github.com/kubeflow/manifests
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubeflow-instance
  namespace: ${releaseNamespace}
spec:
  wait: true
  patches:
  - patch: |
      - op: replace
        path: /spec/type
        value: LoadBalancer
    target:
      kind: Service
      name: istio-ingressgateway
      namespace: istio-system
  - patch: |
     - op: add
       path: /metadata/namespace
       value: default
    target:
      kind: ConfigMap
      name: default-install-config.*
  interval: 6h
  timeout: 15m0s
  path: ./example
  prune: true
  sourceRef:
   kind: GitRepository
   name: kubeflow-instance
   namespace: ${releaseNamespace}
---
#create self-signed certificate
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nutanix-kubeflow-customization
  namespace: ${releaseNamespace}
spec:
  targetNamespace: ${releaseNamespace}
  chart:
    spec:
      chart: nutanix-kubeflow-customization
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: jesse-gonzalez.github.io
        namespace: ${workspaceNamespace}
      version: "0.1.0"
  interval: 30m
  timeout: 20m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: nutanix-kubeflow-customization-0.1.0-defaults
  releaseName: nutanix-kubeflow-customization
---
#kustomize for nutanix objects
